// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvvywsvmbocloxgrnivh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12dnl3c3ZtYm9jbG94Z3JuaXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMjE3MjEsImV4cCI6MjA1NDY5NzcyMX0.Tswv0ep4KfUqsU5ziyyU55rzCbCN2qdk3dj5kPqqdXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);